
package imnprj2.webservices.prj2_3ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapWSImplService", targetNamespace = "http://soap_ws.imnprj2/", wsdlLocation = "http://localhost:8181/SoapWS?wsdl")
public class SoapWSImplService
    extends Service
{

    private final static URL SOAPWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPWSIMPLSERVICE_EXCEPTION;
    private final static QName SOAPWSIMPLSERVICE_QNAME = new QName("http://soap_ws.imnprj2/", "SoapWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8181/SoapWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPWSIMPLSERVICE_WSDL_LOCATION = url;
        SOAPWSIMPLSERVICE_EXCEPTION = e;
    }

    public SoapWSImplService() {
        super(__getWsdlLocation(), SOAPWSIMPLSERVICE_QNAME);
    }

    public SoapWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPWSIMPLSERVICE_QNAME, features);
    }

    public SoapWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPWSIMPLSERVICE_QNAME);
    }

    public SoapWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPWSIMPLSERVICE_QNAME, features);
    }

    public SoapWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapWSInterface
     */
    @WebEndpoint(name = "SoapWSImplPort")
    public SoapWSInterface getSoapWSImplPort() {
        return super.getPort(new QName("http://soap_ws.imnprj2/", "SoapWSImplPort"), SoapWSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapWSInterface
     */
    @WebEndpoint(name = "SoapWSImplPort")
    public SoapWSInterface getSoapWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap_ws.imnprj2/", "SoapWSImplPort"), SoapWSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPWSIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPWSIMPLSERVICE_EXCEPTION;
        }
        return SOAPWSIMPLSERVICE_WSDL_LOCATION;
    }

}
